# Generated by Django 5.2.4 on 2026-04-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='radius_meters',
            field=models.IntegerField(default=50),
        ),
    ]
