# Generated by Django 6.0.2 on 2026-02-16 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('student_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='student_groups.studentgroup'),
        ),
    ]
