# Generated by Django 6.0.2 on 2026-02-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('STUDENT', 'Student'), ('CLASS_REP', 'Class Representative')], default='STUDENT', max_length=10),
        ),
    ]
