# Generated by Django 5.2.4 on 2026-04-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_descriptor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trusted_device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
